//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 03:52:36 PM MST 
//


package tools.print.api.comm_spooler_supervisor;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Comm_Spooler_Supervisor" type="{http://www.example.org/CommonProcessSupervisor}comm_spooler_supervisor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commSpoolerSupervisor"
})
@XmlRootElement(name = "Comm_Spooler_Supervisors")
public class CommSpoolerSupervisors {

    @XmlElement(name = "Comm_Spooler_Supervisor")
    protected List<CommSpoolerSupervisor> commSpoolerSupervisor;

    /**
     * Gets the value of the commSpoolerSupervisor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commSpoolerSupervisor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommSpoolerSupervisor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommSpoolerSupervisor }
     * 
     * 
     */
    public List<CommSpoolerSupervisor> getCommSpoolerSupervisor() {
        if (commSpoolerSupervisor == null) {
            commSpoolerSupervisor = new ArrayList<CommSpoolerSupervisor>();
        }
        return this.commSpoolerSupervisor;
    }

}
