//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.07 at 08:13:29 AM MST 
//


package tools.print.api.modeldriverset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for model-driverset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="model-driverset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Modelid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DriverSetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Driversetid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "model-driverset", propOrder = {
    "model",
    "modelid",
    "driverSetName",
    "driversetid"
})
public class ModelDriverset {

    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Modelid")
    protected int modelid;
    @XmlElement(name = "DriverSetName", required = true)
    protected String driverSetName;
    @XmlElement(name = "Driversetid")
    protected int driversetid;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the modelid property.
     * 
     */
    public int getModelid() {
        return modelid;
    }

    /**
     * Sets the value of the modelid property.
     * 
     */
    public void setModelid(int value) {
        this.modelid = value;
    }

    /**
     * Gets the value of the driverSetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverSetName() {
        return driverSetName;
    }

    /**
     * Sets the value of the driverSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverSetName(String value) {
        this.driverSetName = value;
    }

    /**
     * Gets the value of the driversetid property.
     * 
     */
    public int getDriversetid() {
        return driversetid;
    }

    /**
     * Sets the value of the driversetid property.
     * 
     */
    public void setDriversetid(int value) {
        this.driversetid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
