//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/25/2013 12:35 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.28 at 06:42:59 AM MST 
//


package tools.print.api.protocol;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="protocol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProtocolName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProtocolType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Host_Port_Config" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProtocolVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProtocolPackage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProtocolID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OSID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OSName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OSABBR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sequence_Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OS_ProtocolID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protocol", propOrder = {
    "protocolName",
    "protocolType",
    "hostPortConfig",
    "protocolVersion",
    "protocolPackage",
    "protocolID",
    "osid",
    "osName",
    "osabbr",
    "sequenceNumber"
})
public class Protocol {

    @XmlElement(name = "ProtocolName", required = true)
    protected String protocolName;
    @XmlElement(name = "ProtocolType", required = true)
    protected String protocolType;
    @XmlElement(name = "Host_Port_Config", required = true)
    protected String hostPortConfig;
    @XmlElement(name = "ProtocolVersion", required = true)
    protected String protocolVersion;
    @XmlElement(name = "ProtocolPackage", required = true)
    protected String protocolPackage;
    @XmlElement(name = "ProtocolID")
    protected int protocolID;
    @XmlElement(name = "OSID")
    protected int osid;
    @XmlElement(name = "OSName", required = true)
    protected String osName;
    @XmlElement(name = "OSABBR", required = true)
    protected String osabbr;
    @XmlElement(name = "Sequence_Number")
    protected int sequenceNumber;
    @XmlAttribute(name = "OS_ProtocolID")
    protected Integer osProtocolID;

    /**
     * Gets the value of the protocolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolName() {
        return protocolName;
    }

    /**
     * Sets the value of the protocolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolName(String value) {
        this.protocolName = value;
    }

    /**
     * Gets the value of the protocolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolType() {
        return protocolType;
    }

    /**
     * Sets the value of the protocolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolType(String value) {
        this.protocolType = value;
    }

    /**
     * Gets the value of the hostPortConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostPortConfig() {
        return hostPortConfig;
    }

    /**
     * Sets the value of the hostPortConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostPortConfig(String value) {
        this.hostPortConfig = value;
    }

    /**
     * Gets the value of the protocolVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolVersion() {
        return protocolVersion;
    }

    /**
     * Sets the value of the protocolVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolVersion(String value) {
        this.protocolVersion = value;
    }

    /**
     * Gets the value of the protocolPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolPackage() {
        return protocolPackage;
    }

    /**
     * Sets the value of the protocolPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolPackage(String value) {
        this.protocolPackage = value;
    }

    /**
     * Gets the value of the protocolID property.
     * 
     */
    public int getProtocolID() {
        return protocolID;
    }

    /**
     * Sets the value of the protocolID property.
     * 
     */
    public void setProtocolID(int value) {
        this.protocolID = value;
    }

    /**
     * Gets the value of the osid property.
     * 
     */
    public int getOSID() {
        return osid;
    }

    /**
     * Sets the value of the osid property.
     * 
     */
    public void setOSID(int value) {
        this.osid = value;
    }

    /**
     * Gets the value of the osName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSName() {
        return osName;
    }

    /**
     * Sets the value of the osName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSName(String value) {
        this.osName = value;
    }

    /**
     * Gets the value of the osabbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSABBR() {
        return osabbr;
    }

    /**
     * Sets the value of the osabbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSABBR(String value) {
        this.osabbr = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     */
    public int getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     */
    public void setSequenceNumber(int value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the osProtocolID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOSProtocolID() {
        return osProtocolID;
    }

    /**
     * Sets the value of the osProtocolID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOSProtocolID(Integer value) {
        this.osProtocolID = value;
    }

}
