//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.07 at 06:59:59 AM MST 
//


package tools.print.api.modeldriver;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for modeldriver complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modeldriver">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Modelid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DriverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DriverModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Driverid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modeldriver", propOrder = {
    "model",
    "modelid",
    "driverName",
    "driverModel",
    "driverid"
})
public class Modeldriver {

    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Modelid")
    protected int modelid;
    @XmlElement(name = "DriverName", required = true)
    protected String driverName;
    @XmlElement(name = "DriverModel", required = true)
    protected String driverModel;
    @XmlElement(name = "Driverid")
    protected int driverid;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the modelid property.
     * 
     */
    public int getModelid() {
        return modelid;
    }

    /**
     * Sets the value of the modelid property.
     * 
     */
    public void setModelid(int value) {
        this.modelid = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the driverModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverModel() {
        return driverModel;
    }

    /**
     * Sets the value of the driverModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverModel(String value) {
        this.driverModel = value;
    }

    /**
     * Gets the value of the driverid property.
     * 
     */
    public int getDriverid() {
        return driverid;
    }

    /**
     * Sets the value of the driverid property.
     * 
     */
    public void setDriverid(int value) {
        this.driverid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
