//
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 07:27:12 AM MDT 
//


package tools.print.api.korequest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for korequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="korequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KeyopRequestID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RequestorEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestorTieline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestorExtPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeSubmitted" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceSerial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="E2ECategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CityID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Building" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BuildingID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Room" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CCEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReqStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Solution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KeyopUserid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="KeyopName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeFinished" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ClosedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerContacted" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="KeyopTimeStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="KeyopTimeFinish" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CEReferralNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CEReferralDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="HDReferralNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HDReferralDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="BondReqNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CloseCodeID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="KeyopFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KOReqNotes" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "korequest", propOrder = {
    "keyopRequestID",
    "requestorEmail",
    "requestorName",
    "requestorTieline",
    "requestorExtPhone",
    "timeSubmitted",
    "deviceID",
    "deviceName",
    "deviceSerial",
    "deviceType",
    "tier",
    "e2ECategory",
    "city",
    "cityID",
    "building",
    "buildingID",
    "floor",
    "room",
    "description",
    "ccEmail",
    "reqStatus",
    "solution",
    "keyopUserid",
    "keyopName",
    "timeFinished",
    "closedBy",
    "customerContacted",
    "keyopTimeStart",
    "keyopTimeFinish",
    "ceReferralNum",
    "ceReferralDate",
    "hdReferralNum",
    "hdReferralDate",
    "bondReqNum",
    "closeCodeID",
    "keyopFirstName",
    "keyopLastName",
    "vendorID",
    "keyopCompanyID",
    "keyopCompanyName",
    "koReqNotes"
})

@XmlRootElement(name = "KORequests")
public class KORequest {
	
    @XmlElement(name = "KeyopRequestID")
    protected int keyopRequestID;
    @XmlElement(name = "RequestorEmail", required = true)
    protected String requestorEmail;
    @XmlElement(name = "RequestorName", required = true)
    protected String requestorName;
    @XmlElement(name = "RequestorTieline", required = true)
    protected String requestorTieline;
    @XmlElement(name = "RequestorExtPhone", required = true)
    protected String requestorExtPhone;
    @XmlElement(name = "TimeSubmitted", required = true)
    protected String timeSubmitted;
    @XmlElement(name = "DeviceID")
    protected int deviceID;
    @XmlElement(name = "DeviceName", required = true)
    protected String deviceName;
    @XmlElement(name = "DeviceSerial", required = true)
    protected String deviceSerial;
    @XmlElement(name = "DeviceType", required = true)
    protected String deviceType;
    @XmlElement(name = "Tier", required = true)
    protected String tier;
    @XmlElement(name = "E2ECategory", required = true)
    protected String e2ECategory;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "CityID")
    protected int cityID;
    @XmlElement(name = "Building", required = true)
    protected String building;
    @XmlElement(name = "BuildingID")
    protected int buildingID;
    @XmlElement(name = "Floor", required = true)
    protected String floor;
    @XmlElement(name = "Room", required = true)
    protected String room;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "CCEmail", required = true)
    protected String ccEmail;
    @XmlElement(name = "ReqStatus", required = true)
    protected String reqStatus;
    @XmlElement(name = "Solution", required = true)
    protected String solution;
    @XmlElement(name = "KeyopUserid")
    protected int keyopUserid;
    @XmlElement(name = "KeyopName", required = true)
    protected String keyopName;
    @XmlElement(name = "TimeFinished", required = true)
    protected String timeFinished;
    @XmlElement(name = "ClosedBy", required = true)
    protected String closedBy;
    @XmlElement(name = "CustomerContacted", required = true)
    protected String customerContacted;
    @XmlElement(name = "KeyopTimeStart", required = true)
    protected String keyopTimeStart;
    @XmlElement(name = "KeyopTimeFinish", required = true)
    protected String keyopTimeFinish;
    @XmlElement(name = "CEReferralNum", required = true)
    protected String ceReferralNum;
    @XmlElement(name = "CEReferralDate", required = true)
    protected String ceReferralDate;
    @XmlElement(name = "HDReferralNum", required = true)
    protected String hdReferralNum;
    @XmlElement(name = "HDReferralDate", required = true)
    protected String hdReferralDate;
    @XmlElement(name = "BondReqNum", required = true)
    protected String bondReqNum;
    @XmlElement(name = "CloseCodeID")
    protected int closeCodeID;
    @XmlElement(name = "KeyopFirstName")
    protected String keyopFirstName;
    @XmlElement(name = "KeyopLastName")
    protected String keyopLastName;
    @XmlElement(name = "VendorID")
    protected int vendorID;
    @XmlElement(name = "KeyopCompanyID")
    protected int keyopCompanyID;
    @XmlElement(name = "KeyopCompanyName")
    protected String keyopCompanyName;
    @XmlElement(name = "KeyopRequestNotes")
    protected List<KORequest.KOReqNotes> koReqNotes;

    /**
     * Gets the value of the keyopRequestID property.
     * 
     */
    public int getKeyopRequestID() {
        return keyopRequestID;
    }

    /**
     * Sets the value of the keyopRequestID property.
     * 
     */
    public void setKeyopRequestID(int value) {
        this.keyopRequestID = value;
    }

    /**
     * Gets the value of the requestorEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorEmail() {
        return requestorEmail;
    }

    /**
     * Sets the value of the requestorEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorEmail(String value) {
        this.requestorEmail = value;
    }

    /**
     * Gets the value of the requestorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorName() {
        return requestorName;
    }

    /**
     * Sets the value of the requestorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorName(String value) {
        this.requestorName = value;
    }

    /**
     * Gets the value of the requestorTieline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorTieline() {
        return requestorTieline;
    }

    /**
     * Sets the value of the requestorTieline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorTieline(String value) {
        this.requestorTieline = value;
    }

    /**
     * Gets the value of the requestorExtPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorExtPhone() {
        return requestorExtPhone;
    }

    /**
     * Sets the value of the requestorExtPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorExtPhone(String value) {
        this.requestorExtPhone = value;
    }

    /**
     * Gets the value of the timeSubmitted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTimeSubmitted() {
        return timeSubmitted;
    }

    /**
     * Sets the value of the timeSubmitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeSubmitted(String value) {
    	this.timeSubmitted = value;
    }

    /**
     * Gets the value of the deviceID property.
     * 
     */
    public int getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     */
    public void setDeviceID(int value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

    /**
     * Gets the value of the deviceSerial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceSerial() {
        return deviceSerial;
    }

    /**
     * Sets the value of the deviceSerial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceSerial(String value) {
        this.deviceSerial = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the tier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTier() {
        return tier;
    }

    /**
     * Sets the value of the tier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTier(String value) {
        this.tier = value;
    }

    /**
     * Gets the value of the e2ECategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE2ECategory() {
        return e2ECategory;
    }

    /**
     * Sets the value of the e2ECategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE2ECategory(String value) {
        this.e2ECategory = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the cityID property.
     * 
     */
    public int getCityID() {
        return cityID;
    }

    /**
     * Sets the value of the cityID property.
     * 
     */
    public void setCityID(int value) {
        this.cityID = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilding(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the buildingID property.
     * 
     */
    public int getBuildingID() {
        return buildingID;
    }

    /**
     * Sets the value of the buildingID property.
     * 
     */
    public void setBuildingID(int value) {
        this.buildingID = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloor(String value) {
        this.floor = value;
    }

    /**
     * Gets the value of the room property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoom(String value) {
        this.room = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the ccEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCEmail() {
        return ccEmail;
    }

    /**
     * Sets the value of the ccEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCEmail(String value) {
        this.ccEmail = value;
    }

    /**
     * Gets the value of the reqStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqStatus() {
        return reqStatus;
    }

    /**
     * Sets the value of the reqStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqStatus(String value) {
        this.reqStatus = value;
    }

    /**
     * Gets the value of the solution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolution() {
        return solution;
    }

    /**
     * Sets the value of the solution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolution(String value) {
        this.solution = value;
    }

    /**
     * Gets the value of the keyopUserid property.
     * 
     */
    public int getKeyopUserid() {
        return keyopUserid;
    }

    /**
     * Sets the value of the keyopUserid property.
     * 
     */
    public void setKeyopUserid(int value) {
        this.keyopUserid = value;
    }

    /**
     * Gets the value of the keyopName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyopName() {
        return keyopName;
    }

    /**
     * Sets the value of the keyopName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyopName(String value) {
        this.keyopName = value;
    }

    /**
     * Gets the value of the timeFinished property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTimeFinished() {
        return timeFinished;
    }

    /**
     * Sets the value of the timeFinished property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeFinished(String value) {
        this.timeFinished = value;
    }

    /**
     * Gets the value of the closedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosedBy() {
        return closedBy;
    }

    /**
     * Sets the value of the closedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedBy(String value) {
        this.closedBy = value;
    }

    /**
     * Gets the value of the customerContacted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getCustomerContacted() {
        return customerContacted;
    }

    /**
     * Sets the value of the customerContacted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerContacted(String value) {
        this.customerContacted = value;
    }

    /**
     * Gets the value of the keyopTimeStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getKeyopTimeStart() {
        return keyopTimeStart;
    }

    /**
     * Sets the value of the keyopTimeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKeyopTimeStart(String value) {
        this.keyopTimeStart = value;
    }

    /**
     * Gets the value of the keyopTimeFinish property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getKeyopTimeFinish() {
        return keyopTimeFinish;
    }

    /**
     * Sets the value of the keyopTimeFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKeyopTimeFinish(String value) {
        this.keyopTimeFinish = value;
    }

    /**
     * Gets the value of the ceReferralNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCEReferralNum() {
        return ceReferralNum;
    }

    /**
     * Sets the value of the ceReferralNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCEReferralNum(String value) {
        this.ceReferralNum = value;
    }

    /**
     * Gets the value of the ceReferralDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getCEReferralDate() {
        return ceReferralDate;
    }

    /**
     * Sets the value of the ceReferralDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCEReferralDate(String value) {
        this.ceReferralDate = value;
    }

    /**
     * Gets the value of the hdReferralNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDReferralNum() {
        return hdReferralNum;
    }

    /**
     * Sets the value of the hdReferralNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDReferralNum(String value) {
        this.hdReferralNum = value;
    }

    /**
     * Gets the value of the hdReferralDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getHDReferralDate() {
        return hdReferralDate;
    }

    /**
     * Sets the value of the hdReferralDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHDReferralDate(String value) {
        this.hdReferralDate = value;
    }

    /**
     * Gets the value of the bondReqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondReqNum() {
        return bondReqNum;
    }

    /**
     * Sets the value of the bondReqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondReqNum(String value) {
        this.bondReqNum = value;
    }

    /**
     * Gets the value of the closeCodeID property.
     * 
     */
    public int getCloseCodeID() {
        return closeCodeID;
    }

    /**
     * Sets the value of the closeCodeID property.
     * 
     */
    public void setCloseCodeID(int value) {
        this.closeCodeID = value;
    }
    
    /**
     * Gets the value of the keyopFirstName property.
     * 
     */
    public String getKeyopFirstName() {
        return keyopFirstName;
    }

    /**
     * Sets the value of the keyopFirstName property.
     * 
     */
    public void setKeyopFirstName(String value) {
        this.keyopFirstName = value;
    }
    
    /**
     * Gets the value of the keyopLastName property.
     * 
     */
    public String getKeyopLastName() {
        return keyopLastName;
    }

    /**
     * Sets the value of the keyopLastName property.
     * 
     */
    public void setKeyopLastName(String value) {
        this.keyopLastName = value;
    }
    
    /**
     * Gets the value of the vendorID property.
     * 
     */
    public int getVendorID() {
        return vendorID;
    }

    /**
     * Sets the value of the vendorID property.
     * 
     */
    public void setVendorID(int value) {
        this.vendorID = value;
    }
    
    /**
     * Gets the value of the keyopCompanyID property.
     * 
     */
    public int getKeyopCompanyID() {
        return keyopCompanyID;
    }

    /**
     * Sets the value of the keyopCompanyID property.
     * 
     */
    public void setKeyopCompanyID(int value) {
        this.keyopCompanyID = value;
    }
    
    /**
     * Gets the value of the keyopCompanyName property.
     * 
     */
    public String getKkeyopCompanyName() {
        return keyopCompanyName;
    }

    /**
     * Sets the value of the keyopLastName property.
     * 
     */
    public void setKeyopCompanyName(String value) {
        this.keyopCompanyName = value;
    }

    /**
     * Gets the value of the koReqNotes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the koReqNotes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKOReqNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Korequest.KOReqNotes }
     * 
     * 
     */
    public List<KORequest.KOReqNotes> getKOReqNotes() {
        if (koReqNotes == null) {
            koReqNotes = new ArrayList<KORequest.KOReqNotes>();
        }
        return this.koReqNotes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notes"
    })
    public static class KOReqNotes {

        @XmlElement(name = "Notes", required = true)
        protected String notes;

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

    }

}