//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 07:27:12 AM MDT 
//


package tools.print.api.korequest;

import javax.xml.bind.annotation.XmlRegistry;

//import tools.print.api.Korequest;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tools.print.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tools.print.api
     * 
     */
    public ObjectFactory() {
    }
    
    /**
     * Create an instance of {@link KORequests }
     * 
     */
    public KORequests createKORequests() {
        return new KORequests();
    }

    /**
     * Create an instance of {@link KORequest }
     * 
     */
    public KORequest createKORequest() {
        return new KORequest();
    }

    /**
     * Create an instance of {@link Korequest.KOReqNotes }
     * 
     */
    public KORequest.KOReqNotes createKORequestsKOReqNotes() {
        return new KORequest.KOReqNotes();
    }

}
