//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/25/2013 12:35 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.25 at 06:48:37 AM MST 
//


package tools.print.api.device;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for device complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="device">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Geo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Building" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Room" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RoomAccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WebVisible" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Installable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Duplex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Dipp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FaxNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPSubnet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPGateway" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPHostname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LANDrop" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="E2ECategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DriverSetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClientDefType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CommPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Spooler" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpoolerPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Supervisor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupervisorPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FTPSite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConfidentialPrint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KOCompanyID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="VendorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IGSKeyop" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPDS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Package" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DriverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DriverPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConfigFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HelpFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Monitor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MonitorFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FileList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefaultType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Proc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PrtAttributes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChangeINI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OptionsFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeleteDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceFunctions" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Functions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "device", propOrder = {
    "deviceID",
    "geo",
    "country",
    "state",
    "city",
    "building",
    "floor",
    "deviceName",
    "status",
    "room",
    "roomAccess",
    "lpName",
    "webVisible",
    "installable",
    "port",
    "duplex",
    "dipp",
    "faxNumber",
    "ipDomain",
    "ipSubnet",
    "ipGateway",
    "ipHostname",
    "ipAddress",
    "lanDrop",
    "model",
    "e2ECategory",
    "driverSetName",
    "clientDefType",
    "serverName",
    "comm",
    "commPort",
    "spooler",
    "spoolerPort",
    "supervisor",
    "supervisorPort",
    "ftpSite",
    "confidentialPrint",
    "koCompanyID",
    "vendorName",
    "igsKeyop",
    "ipds",
    "serialNumber",
    "os",
    "_package",
    "version",
    "driverName",
    "dataFile",
    "driverPath",
    "configFile",
    "helpFile",
    "monitor",
    "monitorFile",
    "fileList",
    "defaultType",
    "proc",
    "procFile",
    "prtAttributes",
    "changeINI",
    "optionsFileName",
    "installDate",
    "modifiedDate",
    "deleteDate",
    "deviceFunctions"
})
public class Device {

    @XmlElement(name = "DeviceID")
    protected int deviceID;
    @XmlElement(name = "Geo", required = true)
    protected String geo;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "Building", required = true)
    protected String building;
    @XmlElement(name = "Floor", required = true)
    protected String floor;
    @XmlElement(name = "DeviceName", required = true)
    protected String deviceName;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Room", required = true)
    protected String room;
    @XmlElement(name = "RoomAccess", required = true)
    protected String roomAccess;
    @XmlElement(name = "LPName", required = true)
    protected String lpName;
    @XmlElement(name = "WebVisible", required = true)
    protected String webVisible;
    @XmlElement(name = "Installable", required = true)
    protected String installable;
    @XmlElement(name = "Port", required = true)
    protected String port;
    @XmlElement(name = "Duplex", required = true)
    protected String duplex;
    @XmlElement(name = "Dipp", required = true)
    protected String dipp;
    @XmlElement(name = "FaxNumber", required = true)
    protected String faxNumber;
    @XmlElement(name = "IPDomain", required = true)
    protected String ipDomain;
    @XmlElement(name = "IPSubnet", required = true)
    protected String ipSubnet;
    @XmlElement(name = "IPGateway", required = true)
    protected String ipGateway;
    @XmlElement(name = "IPHostname", required = true)
    protected String ipHostname;
    @XmlElement(name = "IPAddress", required = true)
    protected String ipAddress;
    @XmlElement(name = "LANDrop", required = true)
    protected String lanDrop;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "E2ECategory", required = true)
    protected String e2ECategory;
    @XmlElement(name = "DriverSetName", required = true)
    protected String driverSetName;
    @XmlElement(name = "ClientDefType", required = true)
    protected String clientDefType;
    @XmlElement(name = "ServerName", required = true)
    protected String serverName;
    @XmlElement(name = "Comm", required = true)
    protected String comm;
    @XmlElement(name = "CommPort", required = true)
    protected String commPort;
    @XmlElement(name = "Spooler", required = true)
    protected String spooler;
    @XmlElement(name = "SpoolerPort", required = true)
    protected String spoolerPort;
    @XmlElement(name = "Supervisor", required = true)
    protected String supervisor;
    @XmlElement(name = "SupervisorPort", required = true)
    protected String supervisorPort;
    @XmlElement(name = "FTPSite", required = true)
    protected String ftpSite;
    @XmlElement(name = "ConfidentialPrint", required = true)
    protected String confidentialPrint;
    @XmlElement(name = "KOCompanyID")
    protected int koCompanyID;
    @XmlElement(name = "VendorName", required = true)
    protected String vendorName;
    @XmlElement(name = "IGSKeyop", required = true)
    protected String igsKeyop;
    @XmlElement(name = "IPDS", required = true)
    protected String ipds;
    @XmlElement(name = "SerialNumber", required = true)
    protected String serialNumber;
    @XmlElement(name = "OS", required = true)
    protected String os;
    @XmlElement(name = "Package", required = true)
    protected String _package;
    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "DriverName", required = true)
    protected String driverName;
    @XmlElement(name = "DataFile", required = true)
    protected String dataFile;
    @XmlElement(name = "DriverPath", required = true)
    protected String driverPath;
    @XmlElement(name = "ConfigFile", required = true)
    protected String configFile;
    @XmlElement(name = "HelpFile", required = true)
    protected String helpFile;
    @XmlElement(name = "Monitor", required = true)
    protected String monitor;
    @XmlElement(name = "MonitorFile", required = true)
    protected String monitorFile;
    @XmlElement(name = "FileList", required = true)
    protected String fileList;
    @XmlElement(name = "DefaultType", required = true)
    protected String defaultType;
    @XmlElement(name = "Proc", required = true)
    protected String proc;
    @XmlElement(name = "ProcFile", required = true)
    protected String procFile;
    @XmlElement(name = "PrtAttributes", required = true)
    protected String prtAttributes;
    @XmlElement(name = "ChangeINI", required = true)
    protected String changeINI;
    @XmlElement(name = "OptionsFileName", required = true)
    protected String optionsFileName;
    @XmlElement(name = "InstallDate", required = true)
    protected String installDate;
    @XmlElement(name = "ModifiedDate", required = true)
    protected String modifiedDate;
    @XmlElement(name = "DeleteDate", required = true)
    protected String deleteDate;
    @XmlElement(name = "DeviceFunctions")
    protected List<Device.DeviceFunctions> deviceFunctions;

    /**
     * Gets the value of the deviceID property.
     * 
     */
    public int getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     */
    public void setDeviceID(int value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the geo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeo() {
        return geo;
    }

    /**
     * Sets the value of the geo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeo(String value) {
        this.geo = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilding(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloor(String value) {
        this.floor = value;
    }

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the room property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoom(String value) {
        this.room = value;
    }

    /**
     * Gets the value of the roomAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomAccess() {
        return roomAccess;
    }

    /**
     * Sets the value of the roomAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomAccess(String value) {
        this.roomAccess = value;
    }

    /**
     * Gets the value of the lpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLPName() {
        return lpName;
    }

    /**
     * Sets the value of the lpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLPName(String value) {
        this.lpName = value;
    }

    /**
     * Gets the value of the webVisible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebVisible() {
        return webVisible;
    }

    /**
     * Sets the value of the webVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebVisible(String value) {
        this.webVisible = value;
    }

    /**
     * Gets the value of the installable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallable() {
        return installable;
    }

    /**
     * Sets the value of the installable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallable(String value) {
        this.installable = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the duplex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuplex() {
        return duplex;
    }

    /**
     * Sets the value of the duplex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuplex(String value) {
        this.duplex = value;
    }

    /**
     * Gets the value of the dipp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDipp() {
        return dipp;
    }

    /**
     * Sets the value of the dipp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDipp(String value) {
        this.dipp = value;
    }

    /**
     * Gets the value of the faxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * Sets the value of the faxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNumber(String value) {
        this.faxNumber = value;
    }

    /**
     * Gets the value of the ipDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPDomain() {
        return ipDomain;
    }

    /**
     * Sets the value of the ipDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPDomain(String value) {
        this.ipDomain = value;
    }

    /**
     * Gets the value of the ipSubnet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPSubnet() {
        return ipSubnet;
    }

    /**
     * Sets the value of the ipSubnet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPSubnet(String value) {
        this.ipSubnet = value;
    }

    /**
     * Gets the value of the ipGateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPGateway() {
        return ipGateway;
    }

    /**
     * Sets the value of the ipGateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPGateway(String value) {
        this.ipGateway = value;
    }

    /**
     * Gets the value of the ipHostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPHostname() {
        return ipHostname;
    }

    /**
     * Sets the value of the ipHostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPHostname(String value) {
        this.ipHostname = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the lanDrop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANDrop() {
        return lanDrop;
    }

    /**
     * Sets the value of the lanDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANDrop(String value) {
        this.lanDrop = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the e2ECategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE2ECategory() {
        return e2ECategory;
    }

    /**
     * Sets the value of the e2ECategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE2ECategory(String value) {
        this.e2ECategory = value;
    }

    /**
     * Gets the value of the driverSetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverSetName() {
        return driverSetName;
    }

    /**
     * Sets the value of the driverSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverSetName(String value) {
        this.driverSetName = value;
    }

    /**
     * Gets the value of the clientDefType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientDefType() {
        return clientDefType;
    }

    /**
     * Sets the value of the clientDefType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientDefType(String value) {
        this.clientDefType = value;
    }

    /**
     * Gets the value of the serverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * Sets the value of the serverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerName(String value) {
        this.serverName = value;
    }

    /**
     * Gets the value of the comm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComm() {
        return comm;
    }

    /**
     * Sets the value of the comm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComm(String value) {
        this.comm = value;
    }

    /**
     * Gets the value of the commPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommPort() {
        return commPort;
    }

    /**
     * Sets the value of the commPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommPort(String value) {
        this.commPort = value;
    }

    /**
     * Gets the value of the spooler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpooler() {
        return spooler;
    }

    /**
     * Sets the value of the spooler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpooler(String value) {
        this.spooler = value;
    }

    /**
     * Gets the value of the spoolerPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolerPort() {
        return spoolerPort;
    }

    /**
     * Sets the value of the spoolerPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolerPort(String value) {
        this.spoolerPort = value;
    }

    /**
     * Gets the value of the supervisor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisor() {
        return supervisor;
    }

    /**
     * Sets the value of the supervisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisor(String value) {
        this.supervisor = value;
    }

    /**
     * Gets the value of the supervisorPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisorPort() {
        return supervisorPort;
    }

    /**
     * Sets the value of the supervisorPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisorPort(String value) {
        this.supervisorPort = value;
    }

    /**
     * Gets the value of the ftpSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTPSite() {
        return ftpSite;
    }

    /**
     * Sets the value of the ftpSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTPSite(String value) {
        this.ftpSite = value;
    }

    /**
     * Gets the value of the confidentialPrint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialPrint() {
        return confidentialPrint;
    }

    /**
     * Sets the value of the confidentialPrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialPrint(String value) {
        this.confidentialPrint = value;
    }

    /**
     * Gets the value of the koCompanyID property.
     * 
     */
    public int getKOCompanyID() {
        return koCompanyID;
    }

    /**
     * Sets the value of the koCompanyID property.
     * 
     */
    public void setKOCompanyID(int value) {
        this.koCompanyID = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the igsKeyop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIGSKeyop() {
        return igsKeyop;
    }

    /**
     * Sets the value of the igsKeyop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIGSKeyop(String value) {
        this.igsKeyop = value;
    }

    /**
     * Gets the value of the ipds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPDS() {
        return ipds;
    }

    /**
     * Sets the value of the ipds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPDS(String value) {
        this.ipds = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOS() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOS(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the dataFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFile() {
        return dataFile;
    }

    /**
     * Sets the value of the dataFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFile(String value) {
        this.dataFile = value;
    }

    /**
     * Gets the value of the driverPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverPath() {
        return driverPath;
    }

    /**
     * Sets the value of the driverPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverPath(String value) {
        this.driverPath = value;
    }

    /**
     * Gets the value of the configFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigFile() {
        return configFile;
    }

    /**
     * Sets the value of the configFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigFile(String value) {
        this.configFile = value;
    }

    /**
     * Gets the value of the helpFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpFile() {
        return helpFile;
    }

    /**
     * Sets the value of the helpFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpFile(String value) {
        this.helpFile = value;
    }

    /**
     * Gets the value of the monitor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitor() {
        return monitor;
    }

    /**
     * Sets the value of the monitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitor(String value) {
        this.monitor = value;
    }

    /**
     * Gets the value of the monitorFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitorFile() {
        return monitorFile;
    }

    /**
     * Sets the value of the monitorFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitorFile(String value) {
        this.monitorFile = value;
    }

    /**
     * Gets the value of the fileList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileList() {
        return fileList;
    }

    /**
     * Sets the value of the fileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileList(String value) {
        this.fileList = value;
    }

    /**
     * Gets the value of the defaultType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultType() {
        return defaultType;
    }

    /**
     * Sets the value of the defaultType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultType(String value) {
        this.defaultType = value;
    }

    /**
     * Gets the value of the proc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProc() {
        return proc;
    }

    /**
     * Sets the value of the proc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProc(String value) {
        this.proc = value;
    }

    /**
     * Gets the value of the procFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcFile() {
        return procFile;
    }

    /**
     * Sets the value of the procFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcFile(String value) {
        this.procFile = value;
    }

    /**
     * Gets the value of the prtAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtAttributes() {
        return prtAttributes;
    }

    /**
     * Sets the value of the prtAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtAttributes(String value) {
        this.prtAttributes = value;
    }

    /**
     * Gets the value of the changeINI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeINI() {
        return changeINI;
    }

    /**
     * Sets the value of the changeINI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeINI(String value) {
        this.changeINI = value;
    }

    /**
     * Gets the value of the optionsFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionsFileName() {
        return optionsFileName;
    }

    /**
     * Sets the value of the optionsFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionsFileName(String value) {
        this.optionsFileName = value;
    }

    /**
     * Gets the value of the installDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallDate() {
        return installDate;
    }

    /**
     * Sets the value of the installDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallDate(String value) {
        this.installDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the deleteDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteDate() {
        return deleteDate;
    }

    /**
     * Sets the value of the deleteDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteDate(String value) {
        this.deleteDate = value;
    }

    /**
     * Gets the value of the deviceFunctions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviceFunctions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceFunctions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Device.DeviceFunctions }
     * 
     * 
     */
    public List<Device.DeviceFunctions> getDeviceFunctions() {
        if (deviceFunctions == null) {
            deviceFunctions = new ArrayList<Device.DeviceFunctions>();
        }
        return this.deviceFunctions;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Functions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "functions"
    })
    public static class DeviceFunctions {

        @XmlElement(name = "Functions", required = true)
        protected String functions;

        /**
         * Gets the value of the functions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunctions() {
            return functions;
        }

        /**
         * Sets the value of the functions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunctions(String value) {
            this.functions = value;
        }

    }

}
