//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/25/2013 12:35 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.05 at 08:10:12 AM MST 
//


package tools.print.api.commonprocess;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Functions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Geography" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Building" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Room" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequesterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestedCompletionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Justification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MVS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SAP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RoutingSteps" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Template_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Step" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Action_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Step_Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Assignee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Completed_By" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Schedule_Flow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Schedule_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Completed_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Start_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Schedule_End_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="cproutingid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CPApprovalID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", propOrder = {
    "requestNumber",
    "status",
    "action",
    "deviceName",
    "functions",
    "geography",
    "country",
    "city",
    "building",
    "floor",
    "room",
    "requesterName",
    "emailAddress",
    "phone",
    "requestedCompletionDate",
    "justification",
    "cs",
    "vm",
    "mvs",
    "sap",
    "wts",
    "routingSteps"
})
public class Request {

    @XmlElement(name = "RequestNumber", required = true)
    protected String requestNumber;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "DeviceName", required = true)
    protected String deviceName;
    @XmlElement(name = "Functions", required = true)
    protected String functions;
    @XmlElement(name = "Geography", required = true)
    protected String geography;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "Building", required = true)
    protected String building;
    @XmlElement(name = "Floor", required = true)
    protected String floor;
    @XmlElement(name = "Room", required = true)
    protected String room;
    @XmlElement(name = "RequesterName", required = true)
    protected String requesterName;
    @XmlElement(name = "EmailAddress", required = true)
    protected String emailAddress;
    @XmlElement(name = "Phone", required = true)
    protected String phone;
    @XmlElement(name = "RequestedCompletionDate", required = true)
    protected String requestedCompletionDate;
    @XmlElement(name = "Justification", required = true)
    protected String justification;
    @XmlElement(name = "CS", required = true)
    protected String cs;
    @XmlElement(name = "VM", required = true)
    protected String vm;
    @XmlElement(name = "MVS", required = true)
    protected String mvs;
    @XmlElement(name = "SAP", required = true)
    protected String sap;
    @XmlElement(name = "WTS", required = true)
    protected String wts;
    @XmlElement(name = "RoutingSteps")
    protected List<Request.RoutingSteps> routingSteps;
    @XmlAttribute(name = "CPApprovalID")
    protected Integer cpApprovalID;

    /**
     * Gets the value of the requestNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestNumber() {
        return requestNumber;
    }

    /**
     * Sets the value of the requestNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestNumber(String value) {
        this.requestNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

    /**
     * Gets the value of the functions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctions() {
        return functions;
    }

    /**
     * Sets the value of the functions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctions(String value) {
        this.functions = value;
    }

    /**
     * Gets the value of the geography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeography() {
        return geography;
    }

    /**
     * Sets the value of the geography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeography(String value) {
        this.geography = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilding(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloor(String value) {
        this.floor = value;
    }

    /**
     * Gets the value of the room property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoom(String value) {
        this.room = value;
    }

    /**
     * Gets the value of the requesterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequesterName() {
        return requesterName;
    }

    /**
     * Sets the value of the requesterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequesterName(String value) {
        this.requesterName = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the requestedCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedCompletionDate() {
        return requestedCompletionDate;
    }

    /**
     * Sets the value of the requestedCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedCompletionDate(String value) {
        this.requestedCompletionDate = value;
    }

    /**
     * Gets the value of the justification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustification() {
        return justification;
    }

    /**
     * Sets the value of the justification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustification(String value) {
        this.justification = value;
    }

    /**
     * Gets the value of the cs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCS() {
        return cs;
    }

    /**
     * Sets the value of the cs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCS(String value) {
        this.cs = value;
    }

    /**
     * Gets the value of the vm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVM() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVM(String value) {
        this.vm = value;
    }

    /**
     * Gets the value of the mvs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMVS() {
        return mvs;
    }

    /**
     * Sets the value of the mvs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMVS(String value) {
        this.mvs = value;
    }

    /**
     * Gets the value of the sap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAP() {
        return sap;
    }

    /**
     * Sets the value of the sap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAP(String value) {
        this.sap = value;
    }

    /**
     * Gets the value of the wts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWTS() {
        return wts;
    }

    /**
     * Sets the value of the wts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWTS(String value) {
        this.wts = value;
    }

    /**
     * Gets the value of the routingSteps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routingSteps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoutingSteps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Request.RoutingSteps }
     * 
     * 
     */
    public List<Request.RoutingSteps> getRoutingSteps() {
        if (routingSteps == null) {
            routingSteps = new ArrayList<Request.RoutingSteps>();
        }
        return this.routingSteps;
    }

    /**
     * Gets the value of the cpApprovalID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCPApprovalID() {
        return cpApprovalID;
    }

    /**
     * Sets the value of the cpApprovalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCPApprovalID(Integer value) {
        this.cpApprovalID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Template_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Step" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Action_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Step_Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Assignee" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Completed_By" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Schedule_Flow" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Schedule_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Completed_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Start_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Schedule_End_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="cproutingid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "templateName",
        "step",
        "actionType",
        "stepStatus",
        "assignee",
        "completedBy",
        "scheduleFlow",
        "scheduleDate",
        "completedDate",
        "comments",
        "startDate",
        "scheduleEndDate"
    })
    public static class RoutingSteps {

        @XmlElement(name = "Template_Name", required = true)
        protected String templateName;
        @XmlElement(name = "Step", required = true)
        protected String step;
        @XmlElement(name = "Action_Type", required = true)
        protected String actionType;
        @XmlElement(name = "Step_Status", required = true)
        protected String stepStatus;
        @XmlElement(name = "Assignee", required = true)
        protected String assignee;
        @XmlElement(name = "Completed_By", required = true)
        protected String completedBy;
        @XmlElement(name = "Schedule_Flow", required = true)
        protected String scheduleFlow;
        @XmlElement(name = "Schedule_Date", required = true)
        protected String scheduleDate;
        @XmlElement(name = "Completed_Date", required = true)
        protected String completedDate;
        @XmlElement(name = "Comments", required = true)
        protected String comments;
        @XmlElement(name = "Start_Date", required = true)
        protected String startDate;
        @XmlElement(name = "Schedule_End_Date", required = true)
        protected String scheduleEndDate;
        @XmlAttribute(name = "cproutingid")
        protected Integer cproutingid;

        /**
         * Gets the value of the templateName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTemplateName() {
            return templateName;
        }

        /**
         * Sets the value of the templateName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTemplateName(String value) {
            this.templateName = value;
        }

        /**
         * Gets the value of the step property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStep() {
            return step;
        }

        /**
         * Sets the value of the step property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStep(String value) {
            this.step = value;
        }

        /**
         * Gets the value of the actionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActionType() {
            return actionType;
        }

        /**
         * Sets the value of the actionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionType(String value) {
            this.actionType = value;
        }

        /**
         * Gets the value of the stepStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStepStatus() {
            return stepStatus;
        }

        /**
         * Sets the value of the stepStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStepStatus(String value) {
            this.stepStatus = value;
        }

        /**
         * Gets the value of the assignee property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssignee() {
            return assignee;
        }

        /**
         * Sets the value of the assignee property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssignee(String value) {
            this.assignee = value;
        }

        /**
         * Gets the value of the completedBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompletedBy() {
            return completedBy;
        }

        /**
         * Sets the value of the completedBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompletedBy(String value) {
            this.completedBy = value;
        }

        /**
         * Gets the value of the scheduleFlow property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleFlow() {
            return scheduleFlow;
        }

        /**
         * Sets the value of the scheduleFlow property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleFlow(String value) {
            this.scheduleFlow = value;
        }

        /**
         * Gets the value of the scheduleDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleDate() {
            return scheduleDate;
        }

        /**
         * Sets the value of the scheduleDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleDate(String value) {
            this.scheduleDate = value;
        }

        /**
         * Gets the value of the completedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompletedDate() {
            return completedDate;
        }

        /**
         * Sets the value of the completedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompletedDate(String value) {
            this.completedDate = value;
        }

        /**
         * Gets the value of the comments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComments() {
            return comments;
        }

        /**
         * Sets the value of the comments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComments(String value) {
            this.comments = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDate(String value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the scheduleEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleEndDate() {
            return scheduleEndDate;
        }

        /**
         * Sets the value of the scheduleEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleEndDate(String value) {
            this.scheduleEndDate = value;
        }

        /**
         * Gets the value of the cproutingid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCproutingid() {
            return cproutingid;
        }

        /**
         * Sets the value of the cproutingid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCproutingid(Integer value) {
            this.cproutingid = value;
        }

    }

}
